import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
GPIO.setup(18,GPIO.OUT)
GPIO.setup(22,GPIO.OUT)
GPIO.setup(24,GPIO.OUT)
GPIO.setup(26,GPIO.OUT)
while True:
       print('LED ON 18')
       GPIO.output(18,GPIO.HIGH)
       time.sleep(0.5)
       print('LED off 18 ')
       GPIO.output(18,GPIO.LOW)
       time.sleep(0.5)
       print('LED ON 22')
       GPIO.output(22,GPIO.HIGH)
       time.sleep(0.5)
       print('LED off 22')
       GPIO.output(22,GPIO.LOW)
       time.sleep(0.5)
       print('LED ON 24')
       GPIO.output(24,GPIO.HIGH)
       time.sleep(0.5)
       print('LED off 24')
       GPIO.output(24,GPIO.LOW)
       time.sleep(0.5)
       print('LED ON 26')
       GPIO.output(26,GPIO.HIGH)
       time.sleep(0.5)
       print('LED off 26')
       GPIO.output(26,GPIO.LOW)
       time.sleep(0.5)
